---
- name: Assert required dump variables exist
  tags:
    - mariadb
    - mariadb_dump
  assert:
    that:
      - mariadb_dump_userpassword is defined
      - mariadb_dump_databases is defined
      - mariadb_dump_destinationdir is defined

- name: Include dump vars
  tags:
    - mariadb
    - mariadb_dump
  include_vars: mariadb_dump.yml

- name: Create mariadb_dump_destinationdir
  tags:
    - mariadb
    - mariadb_dump
  become: true
  file:
    state=directory
    path="{{ mariadb_dump_destinationdir }}"
    owner=0
    group=0
    mode=0755

- name: Deploy backupscript
  tags:
    - mariadb
    - mariadb_dump
  become: true
  template:
    src=mariadb_dump.j2
    dest="{{ mariadb_dump_scriptfile }}"
    owner=0
    group=0
    mode=0700

- name: Create cronjob for backupscript
  tags:
    - mariadb
    - mariadb_dump
  become: true
  cron:
    state=present
    job="{{ mariadb_dump_scriptfile }}"
    name=mariadb_backup
    minute=0
    hour="{{ mariadb_dump_crontime.hour }}"
    weekday="{{ mariadb_dump_crontime.dayofweek }}"
