---
- name: restart mariadb
  tags: mariadb
  service: name={{ mariadb_service }} state=restarted

- name: Add additional db users
  tags: mariadb
  with_items: mariadb_additional_users
  mysql_user:
    name={{ item.name }}
    password={{ item.pass|default("foobar") }}
    priv={{ item.priv|default("*.*:ALL") }}
    state=present
    host={{ item.host|default("localhost") }}
    append_privs={{ item.append_privs|default("no") }}

